# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7caa1b63d1bc7b32ce3499c719dea2f96e9ece9587576a082aba4b01fd077d2d107f66156b105a6f2e6455d4e0c6f07aaa9259a1e38ea090eb94d1461deb960b

test:
  secret_key_base: cb59cac018bf1dffd1f6ef970ae53fd1463875986690bd803cbfb4c9335cee86f8d407b659db78c70ffedb7be6c544ffe3c6fb1279d81f49f7d87bdea4feb132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
