# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a60b1c2f64e7b222a5c921084f6a26708a05e6e0eb5a2a1be6ebb145a1baac52294bb726317f22d98bba81f7f760a4a8e67cc28ad7c962de975a2afd1891cd

test:
  secret_key_base: 6579858d228655cbc751d1fe4a85bc0d5f8b7c03d6de4fb707016388c185d9e319ee25877b344825381148820079551cb68752a2f2deca2bd04978952090c1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
