# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
curso_list = [
	[ "Administração: Administração de Empresas","Bacharelado"],
	[ "Administração: Comércio Internacional","Bacharelado"],
	[ "Administração: Empreendedorismo e Sucessão","Bacharelado"],
	[ "Administração: Gestão de Tecnologia da Informação","Bacharelado"],
	[ "Administração: Marketing","Bacharelado"],
	[ "Arquitetura e Urbanismo","Bacharelado"],
	[ "Ciência da Computação","Bacharelado"],
	[ "Ciência e Inovação em Alimentos","Bacharelado"],
	[ "Ciências Aeronáuticas","Bacharelado"],
	[ "Ciências Biológicas","Bacharelado/Licenciatura"],
	[ "Ciências Contábeis - Controladoria e Finanças","Bacharelado"],
	[ "Ciências Econômicas","Bacharelado"],
	[ "Ciências Sociais","Licenciatura/Bacharelado"],
	[ "Comunicação Social: Jornalismo","Bacharelado"],
	[ "Comunicação Social: Publicidade e Propaganda","Bacharelado"],
	[ "Comunicação Social: Relações Públicas","Bacharelado"],
	[ "Direito","Bacharelado"],
	[ "Educação Física","Bacharelado/Licenciatura"],
	[ "Enfermagem","Bacharelado"],
	[ "Engenharia Civil","Bacharelado"],
	[ "Engenharia de Computação","Bacharelado"],
	[ "Engenharia de Controle e Automação","Bacharelado"],
	[ "Engenharia de Software","Bacharelado"],
	[ "Engenharia Elétrica","Bacharelado"],
	[ "Engenharia Mecânica","Bacharelado"],
	[ "Engenharia de Produção","Bacharelado"],
	[ "Engenharia Química","Bacharelado"],
	[ "Escrita Criativa","Tecnólogo"],
	[ "Farmácia","Bacharelado"],
	[ "Filosofia","Bacharelado/Licenciatura"],
	[ "Física","Licenciatura"],
	[ "Física - Formação em Física Médica","Bacharelado"],
	[ "Física - Formação em Geofísica","Bacharelado"],
	[ "Fisioterapia","Bacharelado"],
	[ "Gastronomia","Tecnólogo"],
	[ "Geografia","Bacharelado/Licenciatura"],
	[ "Gestão de Turismo","Tecnólogo"],
	[ "História","Bacharelado/Licenciatura"],
	[ "Hotelaria","Tecnólogo"],
	[ "Letras","Licenciatura"],
	[ "Matemática","Licenciatura"],
	[ "Matemática - Formação em Matemática Empresarial","Bacharelado"],
	[ "Medicina","Bacharelado"],
	[ "Nutrição","Bacharelado"],
	[ "Odontologia","Bacharelado"],
	[ "Pedagogia","Licenciatura"],
	[ "Produção Audiovisual / Cinema e Vídeo","Tecnólogo"],
	[ "Psicologia","Bacharelado"],
	[ "Química","Licenciatura"],
	[ "Química - Formação em Química Industrial","Bacharelado"],
	[ "Serviço Social","Bacharelado"],
	[ "Sistemas de Informação","Bacharelado"],
	[ "Teologia","Bacharelado"]
]

curso_list.each do |curso|
	Curso.create(nome: curso[0], grau:curso[1])
end

disciplina_list = [
	["Matemática Discreta (Cc)",4],
	["Cálculo A",4],
	["Geometria Analitica",2],
	["Algoritmos e Programacao I",6],
	["Introducao A Ciencia da Computacao",4],
	["Cálculo B",4],
	["Algebra Matricial",2],
	["Algoritmos e Programacao II",6],
	["Logica para Computacao",4],
	["Linguagens Formais",4],
	["Organizacao e Arquit. de Computadores I",4],
	["Modelagem de Software",4],
	["Laboratorio de Banco de Dados I",2],
	["Algoritmos e Programacao III",6],
	["Paradigmas de Linguagens de Programacao",4],
	["Teoria da Computacao",4],
	["Organizacao e Arquit. de Computadores II",4],
	["Programacao para Software Basico",4],
	["Modelagem Conceit. e Proj. de Banco Dados",4],
	["Complexidade e Otimizacao",4],
	["Técnicas de Programação",4],
	["Computacao Grafica I",4],
	["Organizacao e Arquit. de Computadores III",4],
	["Compiladores",4],
	["Métodos Estatísticos",4],
	["Gerencia de Projetos de Software",4],
	["Projeto de Interfaces",2],
	["Metodos Formais para Computacao",4],
	["Computacao Grafica II",2],
	["Sistemas Operacionais (Cc)",4],
	["Redes de Computadores I",4],
	["Desenvolvimento de Sistemas",4],
	["Implementacao de Banco de Dados",4],
	["Entretenimento Digital",2],
	["Inteligencia Artificial",4],
	["Metodos Computacionais (Cc)",4],
	["Programacao de Perifericos (Cc)",2],
	["Redes de Computadores II",4],
	["Laboratorio de Redes de Computadores",2],
	["Humanismo e Cultura Religiosa",4],
	["Trabalho de Conclusao I",4],
	["Avaliacao de Desempenho de Sistemas",4],
	["Redes de Computadores III",4],
	["Programacao Paralela",2],
	["Ética e Filosofia da Ciência",4],
	["Empreendimentos Empresariais",4],
	["Trabalho de Conclusao II",4],
	["Sistemas Embarcados",4],
	["Programacao Distribuida",4]
]

disciplina_list.each do |disciplina|
	Disciplina.create(nome: disciplina[0], creditos:disciplina[1])
end
