curso_list = [
	[ "Administração: Administração de Empresas","Bacharelado"],
	[ "Administração: Comércio Internacional","Bacharelado"],
	[ "Administração: Empreendedorismo e Sucessão","Bacharelado"],
	[ "Administração: Gestão de Tecnologia da Informação","Bacharelado"],
	[ "Administração: Marketing","Bacharelado"],
	[ "Arquitetura e Urbanismo","Bacharelado"],
	[ "Ciência da Computação","Bacharelado"],
	[ "Ciência e Inovação em Alimentos","Bacharelado"],
	[ "Ciências Aeronáuticas","Bacharelado"],
	[ "Ciências Biológicas","Bacharelado/Licenciatura"],
	[ "Ciências Contábeis - Controladoria e Finanças","Bacharelado"],
	[ "Ciências Econômicas","Bacharelado"],
	[ "Ciências Sociais","Licenciatura/Bacharelado"],
	[ "Comunicação Social: Jornalismo","Bacharelado"],
	[ "Comunicação Social: Publicidade e Propaganda","Bacharelado"],
	[ "Comunicação Social: Relações Públicas","Bacharelado"],
	[ "Direito","Bacharelado"],
	[ "Educação Física","Bacharelado/Licenciatura"],
	[ "Enfermagem","Bacharelado"],
	[ "Engenharia Civil","Bacharelado"],
	[ "Engenharia de Computação","Bacharelado"],
	[ "Engenharia de Controle e Automação","Bacharelado"],
	[ "Engenharia de Software","Bacharelado"],
	[ "Engenharia Elétrica","Bacharelado"],
	[ "Engenharia Mecânica","Bacharelado"],
	[ "Engenharia de Produção","Bacharelado"],
	[ "Engenharia Química","Bacharelado"],
	[ "Escrita Criativa","Tecnólogo"],
	[ "Farmácia","Bacharelado"],
	[ "Filosofia","Bacharelado/Licenciatura"],
	[ "Física","Licenciatura"],
	[ "Física - Formação em Física Médica","Bacharelado"],
	[ "Física - Formação em Geofísica","Bacharelado"],
	[ "Fisioterapia","Bacharelado"],
	[ "Gastronomia","Tecnólogo"],
	[ "Geografia","Bacharelado/Licenciatura"],
	[ "Gestão de Turismo","Tecnólogo"],
	[ "História","Bacharelado/Licenciatura"],
	[ "Hotelaria","Tecnólogo"],
	[ "Letras","Licenciatura"],
	[ "Matemática","Licenciatura"],
	[ "Matemática - Formação em Matemática Empresarial","Bacharelado"],
	[ "Medicina","Bacharelado"],
	[ "Nutrição","Bacharelado"],
	[ "Odontologia","Bacharelado"],
	[ "Pedagogia","Licenciatura"],
	[ "Produção Audiovisual / Cinema e Vídeo","Tecnólogo"],
	[ "Psicologia","Bacharelado"],
	[ "Química","Licenciatura"],
	[ "Química - Formação em Química Industrial","Bacharelado"],
	[ "Serviço Social","Bacharelado"],
	[ "Sistemas de Informação","Bacharelado"],
	[ "Teologia","Bacharelado"]
]

curso_list.each do |curso|
	Curso.create(nome: curso[0], grau:curso[1])
end

disciplina_list = [
	["Algebra Matricial",2,2],
	["Algoritmos e Programação I",6,1],
	["Algoritmos e Programação II",6,2],
	["Algoritmos e Programação III",6,3],
	["Avaliacao de Desempenho de Sistemas",4,7],
	["Compiladores",4,4],
	["Complexidade e Otimizacao",4,4],
	["Computacao Grafica I",4,4],
	["Computacao Grafica II",2,5],
	["Cálculo A",4,1],
	["Cálculo B",4,1],
	["Desenvolvimento de Sistemas",4,6],
	["Empreendimentos Empresariais",4,8],
	["Entretenimento Digital",2,6],
	["Geometria Analitica",2,1],
	["Gerencia de Projetos de Software",4,5],
	["Humanismo e Cultura Religiosa",4,7],
	["Implementacao de Banco de Dados",4,6],
	["Inteligencia Artificial",4,6],
	["Introducao A Ciencia da Computacao",4,1],
	["Laboratorio de Banco de Dados I",2,3],
	["Laboratorio de Redes de Computadores",2,6],
	["Linguagens Formais",4,2],
	["Logica para Computacao",4,2],
	["Matemática Discreta (Cc)",4,1],
	["Metodos Computacionais (Cc)",4,6],
	["Metodos Formais para Computacao",4,5],
	["Modelagem Conceit. e Proj. de Banco Dados",4,4],
	["Modelagem de Software",4,3],
	["Métodos Estatísticos",4,5],
	["Organizacao e Arquit. de Computadores I",4,2],
	["Organizacao e Arquit. de Computadores II",4,3],
	["Organizacao e Arquit. de Computadores III",4,4],
	["Paradigmas de Linguagens de Programação",4,3],
	["Programação Distribuida",4,8],
	["Programação Paralela",2,7],
	["Programação de Perifericos (Cc)",2,6],
	["Programação para Software Basico",4,3],
	["Projeto de Interfaces",2,5],
	["Redes de Computadores I",4,5],
	["Redes de Computadores II",4,6],
	["Redes de Computadores III",4,7],
	["Sistemas Embarcados",4,8],
	["Sistemas Operacionais (Cc)",4,5],
	["Teoria da Computacao",4,3],
	["Trabalho de Conclusao I",4,7],
	["Trabalho de Conclusao II",4,8],
	["Técnicas de Programação",4,4],
	["Ética e Filosofia da Ciência",4,8]
]

disciplina_list.each do |disciplina|
	disc = Disciplina.create(nome: disciplina[0], creditos:disciplina[1], semestre: disciplina[2])
	Curriculo.create(codigo: '4406', curso_id: 7, disciplina_id: disc.id)
end
